name: Deploy Next.js to Cloud Run

on:
  push:
    branches:
      - main  # Jab aap main branch par push karenge tabhi deploy hoga

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: nextjs-app # Aapka manchaha app name
  REGION: us-central1      # Aapka pasandida region

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and Push Docker Image
        run: |
          # Pehle image build karein
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:$GITHUB_SHA .
          # Phir use push karein
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:$GITHUB_SHA